version: '3'

services:
  mainnet:
    build:
      context: .
      dockerfile: docker/Dockerfile
    tty: true
    ports:
      - 1234:1234
    command: /root/fuhon-node
      --api-ip 0.0.0.0
      --repo /root/repo
      --genesis /root/mainnet.car
      --log d
      --bootstrap=/dns4/node.glif.io/tcp/1235/p2p/12D3KooWBF8cpp65hp2u9LK5mh19x67ftAam84z9LsfaquTDSBpt
