/**
 * Copyright Soramitsu Co., Ltd. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef CPP_FILECOIN_CORE_MARKETS_STORAGE__NETWORK_STORAGE_DEAL_STREAM_HPP
#define CPP_FILECOIN_CORE_MARKETS_STORAGE__NETWORK_STORAGE_DEAL_STREAM_HPP

#endif  // CPP_FILECOIN_CORE_MARKETS_STORAGE__NETWORK_STORAGE_DEAL_STREAM_HPP
