/**
 * Copyright Soramitsu Co., Ltd. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef CPP_FILECOIN_CORE_MARKETS_STORAGE__PROTOCOL_RESPONSE_HPP
#define CPP_FILECOIN_CORE_MARKETS_STORAGE__PROTOCOL_RESPONSE_HPP

#endif  // CPP_FILECOIN_CORE_MARKETS_STORAGE__PROTOCOL_RESPONSE_HPP
