name: LSAN

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      name: checkout repo
    - name: cache
      uses: actions/cache@v1.2.0
      env:
        cache-name: cache-filecoin-ffi-proofs
        version: v28
      with:
        path: /var/tmp/filecoin-proof-parameters
        key: build-${{ env.cache-name }}-${{ env.version }}
    - name: checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: install
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build python-setuptools pkg-config ocl-icd-* opencl-headers libhwloc-dev
        sudo python3 -m pip install --upgrade pip
        sudo python3 -m pip install scikit-build cmake requests gitpython gcovr pyyaml
    - name: cmake
      env:
        CC: "clang"
        CXX: "clang++"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # has to be included to access other secrets
        GITHUB_HUNTER_USERNAME: ${{ secrets.GITHUB_HUNTER_USERNAME }}
        GITHUB_HUNTER_TOKEN: ${{ secrets.GITHUB_HUNTER_TOKEN }}
      run: cmake . -GNinja -Bbuild -D LSAN=ON -D TESTING_PROOFS=ON
    - name: build
      run: cmake --build build -- -j2
    - name: run tests
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: cmake --build build --target test
