name: ASAN

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
        name: checkout repo
      - name: cache
        uses: actions/cache@v1.2.0
        env:
          cache-name: cache-filecoin-ffi-proofs
          version: v28
        with:
          path: /var/tmp/filecoin-proof-parameters
          key: build-${{ env.cache-name }}-${{ env.version }}
      - name: install
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build python-setuptools pkg-config ocl-icd-* opencl-headers libhwloc-dev
          sudo python3 -m pip install --upgrade pip
          sudo python3 -m pip install scikit-build cmake requests gitpython gcovr pyyaml
      - name: cmake
        env:
          CC: "clang"
          CXX: "clang++"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # has to be included to access other secrets
          GITHUB_HUNTER_USERNAME: ${{ secrets.HUNTER_USERNAME }}
          GITHUB_HUNTER_TOKEN: ${{ secrets.HUNTER_TOKEN }}
        run: cmake . -GNinja -Bbuild -D ASAN=ON -D TESTING_PROOFS=ON -D TESTING_ACTORS=ON
      - name: build
        run: cmake --build build -- -j2
      - name: run tests
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
          # ASAN container overflow detection is disabled because of false-positives.
          # (https://github.com/google/sanitizers/wiki/AddressSanitizerContainerOverflow#false-positives)
          ASAN_OPTIONS: "halt_on_error=1: detect_container_overflow=0"
        run: cmake --build build --target test
