name: TSAN

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
        name: checkout repo
      - name: cache
        uses: actions/cache@v1.2.0
        env:
          cache-name: cache-filecoin-ffi-proofs
          version: v28
        with:
          path: /var/tmp/filecoin-proof-parameters
          key: build-${{ env.cache-name }}-${{ env.version }}
      - name: install
        run: |
          echo "LIBRARY_PATH=$LIBRARY_PATH:/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib" >> $GITHUB_ENV
          brew install ninja llvm pkg-config libb2 hwloc hidapi
          sudo python3 -m pip install --upgrade pip
          sudo python3 -m pip install scikit-build cmake requests gitpython gcovr pyyaml
      - name: cmake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # has to be included to access other secrets
          GITHUB_HUNTER_USERNAME: ${{ secrets.HUNTER_USERNAME }}
          GITHUB_HUNTER_TOKEN: ${{ secrets.HUNTER_TOKEN }}
          CFLAGS: "-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include"
          CXXFLAGS: "-isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include"
        run: cmake . -GNinja -Bbuild -D TSAN=ON -D TESTING_PROOFS=ON -D TESTING_ACTORS=ON
      - name: build
        run: cmake --build build -- -j2
      - name: run tests
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
          TSAN_OPTIONS: "suppressions=${{ github.workspace }}/.github/workflows/tsan-ignorelist.txt"
        run: cmake --build build --target test

